---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Env:
    Type: String
    Default: ops
    AllowedValues:
      - ops
    Description: The environment name

  Name:
    Type: String
    Description: The name

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Env}-${Name}
      Handler: lambda_function.lambda_handler
      Role: !Ref IAMRoleForLambda
      Runtime: python3.9
      Timeout: 300
      Code:
        S3Bucket: lambda.jiro4989.com
        S3Key: !Sub ${Env}/${Name}.zip
      Environment:
        Variables:
          RETAINING_DAYS: '7'
          RUN: 'false'
      Tags:
        - Key: env
          Value: !Sub ${Env}
        - Key: created_by
          Value: cloudformation

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventsRule.Arn

  EventsRule:
    Type: AWS::Events::Rule
    Properties:
      Description: ’schedule event for lambda’
      ScheduleExpression: 'cron(0 10 * * ? *)'
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: !Sub ${Env}-${Name}

  IAMRoleForLambda:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSLambdaBasicExecutionRole"
      Path: /
      RoleName: !Sub ${Env}-${Name}-lambda
      Policies:
        - PolicyName: !Sub ${Env}-${Name}-lambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:DescribeTags
                  - "cloudformation:DeleteStack"
                  - "cloudformation:DescribeStacks"
                Resource: '*'
