AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
      - prd
      - stg
      - dev
    Description: The environment name

  ProjectName:
    Type: String
    Description: The project name

Resources:
  SessionManagerIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
      Path: /
      RoleName: !Sub ${EnvironmentName}-${ProjectName}-ssm

  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: !Sub ${EnvironmentName}-${ProjectName}-profile
      Path: /
      Roles:
        - !Ref SessionManagerIAMRole

  SessionManagerIAMPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:PutObject"
            Resource: !Sub
              - ${Arn}/*
              - Arn: !ImportValue log-bucket-arn
          - Effect: Allow
            Action:
              - "logs:PutLogEvents"
              - "logs:CreateLogStream"
            Resource:
              - !Sub
                - ${Arn}
                - Arn: !GetAtt EC2LogGroup.Arn
              - !Sub
                - ${Arn}/*
                - Arn: !GetAtt EC2LogGroup.Arn
                
      PolicyName: !Sub ${EnvironmentName}-${ProjectName}-ssm
      Roles:
        - !Ref SessionManagerIAMRole

  EC2LogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub ${EnvironmentName}-${ProjectName}-ssm
      RetentionInDays: 1
      Tags: 
        - Key: created_by
          Value: cloudformation

  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: ami-082c70eb5ed5441a1
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          GroupSet:
            - "Fn::ImportValue": !Sub ${EnvironmentName}-${ProjectName}-private-sg
          SubnetId: !ImportValue
            "Fn::Sub": ${EnvironmentName}-${ProjectName}-private-subnet-a
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ProjectName}-ec2
        - Key: created_by
          Value: cloudformation
      UserData: !Base64 |
        #!/bin/bash
        sudo yum install -y git
        